package persistence

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/slchris/portage-engine/internal/builder"
	"github.com/slchris/portage-engine/internal/catalog"
)

const maxLedgerErrorBytes = 64 * 1024

// LedgerReconcileReport compares the legacy in-memory view with visible
// PostgreSQL shadow rows. Missing/mismatched rows are repaired; extra rows are
// reported because DB-1 must not silently invent legacy queue ownership.
type LedgerReconcileReport struct {
	CheckedAt       time.Time `json:"checked_at"`
	LegacyCount     int       `json:"legacy_count"`
	LedgerCount     int       `json:"ledger_count"`
	Missing         int       `json:"missing"`
	Mismatched      int       `json:"mismatched"`
	RequestMismatch int       `json:"request_mismatch"`
	Extra           int       `json:"extra"`
	Repaired        int       `json:"repaired"`
	Consistent      bool      `json:"consistent"`
	Error           string    `json:"error,omitempty"`
}

// JobLedgerStatus is the low-cardinality runtime status exposed to health and
// the operator UI.
type JobLedgerStatus struct {
	Authority        string                `json:"authority"`
	Writes           uint64                `json:"writes"`
	WriteErrors      uint64                `json:"write_errors"`
	ProjectionErrors uint64                `json:"projection_errors"`
	LastWriteAt      time.Time             `json:"last_write_at,omitempty"`
	LastProjectionAt time.Time             `json:"last_projection_at,omitempty"`
	LastError        string                `json:"last_error,omitempty"`
	LastReconcile    LedgerReconcileReport `json:"last_reconcile"`
}

// JobRepository implements the DB-1 builder.JobLedger contract.
type JobRepository struct {
	db        *Database
	mu        sync.RWMutex
	stats     JobLedgerStatus
	workerMu  sync.Mutex
	workerIDs map[string]cachedWorker
	monitorMu sync.Mutex
	monitorAt time.Time
	monitor   builder.TargetHistoryStatus
}

type cachedWorker struct {
	ID              uuid.UUID
	Heartbeat       time.Time
	CapabilitiesKey string
}

// NewJobRepository creates a shadow job ledger on an initialized DB-1 schema.
func NewJobRepository(db *Database) *JobRepository {
	return &JobRepository{
		db: db, stats: JobLedgerStatus{Authority: "postgresql"},
		workerIDs: make(map[string]cachedWorker),
	}
}

type storedBuildRequest struct {
	ProjectID       string                        `json:"project_id,omitempty"`
	RequestedBy     string                        `json:"requested_by,omitempty"`
	PackageName     string                        `json:"package_name"`
	Version         string                        `json:"version"`
	Arch            string                        `json:"arch"`
	UseFlags        []string                      `json:"use_flags"`
	CloudProvider   string                        `json:"cloud_provider"`
	ProfileID       string                        `json:"profile_id,omitempty"`
	RepositoryIDs   []string                      `json:"repository_ids,omitempty"`
	ResourceClass   string                        `json:"resource_class,omitempty"`
	MachineSpec     map[string]string             `json:"machine_spec"`
	ResolvedContext *catalog.ResolvedBuildContext `json:"resolved_context,omitempty"`
	ConfigBundle    *builder.ConfigBundle         `json:"config_bundle,omitempty"`
	IdempotencyKey  string                        `json:"idempotency_key,omitempty"`
}

func requestDocument(req *builder.BuildRequest) ([]byte, string, error) {
	if req == nil {
		return nil, "", fmt.Errorf("nil build request")
	}
	doc := storedBuildRequest{
		ProjectID: req.ProjectID, RequestedBy: req.RequestedBy,
		PackageName: req.PackageName, Version: req.Version, Arch: req.Arch,
		UseFlags: append([]string(nil), req.UseFlags...), CloudProvider: req.CloudProvider,
		ProfileID: req.ProfileID, RepositoryIDs: append([]string(nil), req.RepositoryIDs...),
		ResourceClass: req.ResourceClass, MachineSpec: req.MachineSpec,
		ResolvedContext: req.ResolvedContext, ConfigBundle: req.ConfigBundle,
		IdempotencyKey: req.IdempotencyKey,
	}
	data, err := json.Marshal(doc)
	if err != nil {
		return nil, "", fmt.Errorf("marshal build request: %w", err)
	}

	// The stored request keeps complete runtime provenance, but idempotency
	// must ignore timestamps generated by resolution itself. Otherwise an
	// identical retry a millisecond later hashes differently and is rejected.
	var digestDoc map[string]any
	if err := json.Unmarshal(data, &digestDoc); err != nil {
		return nil, "", fmt.Errorf("prepare build request digest: %w", err)
	}
	if resolved, ok := digestDoc["resolved_context"].(map[string]any); ok {
		delete(resolved, "resolved_at")
	}
	if bundle, ok := digestDoc["config_bundle"].(map[string]any); ok {
		if metadata, ok := bundle["metadata"].(map[string]any); ok {
			delete(metadata, "created_at")
		}
	}
	delete(digestDoc, "requested_by")
	digestData, err := json.Marshal(digestDoc)
	if err != nil {
		return nil, "", fmt.Errorf("marshal build request digest: %w", err)
	}
	return data, digestBytes(digestData), nil
}

type storedJobStatus struct {
	JobID           string                        `json:"job_id"`
	ProjectID       string                        `json:"project_id,omitempty"`
	RequestedBy     string                        `json:"requested_by,omitempty"`
	Status          string                        `json:"status"`
	PackageName     string                        `json:"package_name"`
	Version         string                        `json:"version"`
	Arch            string                        `json:"arch"`
	CreatedAt       time.Time                     `json:"created_at"`
	UpdatedAt       time.Time                     `json:"updated_at"`
	InstanceID      string                        `json:"instance_id,omitempty"`
	Error           string                        `json:"error,omitempty"`
	ArtifactPath    string                        `json:"artifact_path,omitempty"`
	ArtifactURL     string                        `json:"artifact_url,omitempty"`
	Artifacts       []string                      `json:"artifacts,omitempty"`
	Signed          bool                          `json:"signed,omitempty"`
	ResolvedContext *catalog.ResolvedBuildContext `json:"resolved_context,omitempty"`
	FailedStage     string                        `json:"failed_stage,omitempty"`
}

func statusDocument(status *builder.BuildStatus) ([]byte, string, error) {
	if status == nil {
		return nil, "", fmt.Errorf("nil build status")
	}
	errorText := status.Error
	if len(errorText) > maxLedgerErrorBytes {
		errorText = errorText[:maxLedgerErrorBytes] + "\n[... error truncated in ledger ...]"
	}
	doc := storedJobStatus{
		JobID: status.JobID, ProjectID: status.ProjectID, RequestedBy: status.RequestedBy,
		Status: status.Status, PackageName: status.PackageName,
		Version: status.Version, Arch: status.Arch, CreatedAt: status.CreatedAt,
		UpdatedAt: status.UpdatedAt, InstanceID: status.InstanceID, Error: errorText,
		ArtifactPath: status.ArtifactPath, ArtifactURL: status.ArtifactURL,
		Artifacts: append([]string(nil), status.Artifacts...), Signed: status.Signed,
		ResolvedContext: status.ResolvedContext, FailedStage: status.FailedStage,
	}
	data, err := json.Marshal(doc)
	if err != nil {
		return nil, "", fmt.Errorf("marshal build status: %w", err)
	}
	return data, digestBytes(data), nil
}

func digestBytes(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

// CreateJob inserts a complete request and queued snapshot in one transaction,
// together with its event and outbox row.
func (r *JobRepository) CreateJob(ctx context.Context, req *builder.BuildRequest, status *builder.BuildStatus) (builder.LedgerCreateResult, error) {
	result, err := r.createJob(ctx, req, status, "api")
	r.recordWrite(err)
	return result, err
}

func (r *JobRepository) createJob(ctx context.Context, req *builder.BuildRequest, status *builder.BuildStatus, source string) (builder.LedgerCreateResult, error) {
	requestJSON, requestDigest, err := requestDocument(req)
	if err != nil {
		return builder.LedgerCreateResult{}, err
	}
	statusJSON, statusDigest, err := statusDocument(status)
	if err != nil {
		return builder.LedgerCreateResult{}, err
	}
	requirements, err := builder.PhaseCapabilityRequirements(req, "provision")
	if err != nil {
		return builder.LedgerCreateResult{}, err
	}
	requirementsJSON, err := json.Marshal(requirements)
	if err != nil {
		return builder.LedgerCreateResult{}, fmt.Errorf("marshal scheduler requirements: %w", err)
	}
	result := builder.LedgerCreateResult{}
	err = r.db.WithTx(ctx, pgx.TxOptions{}, func(q Querier) error {
		projectID, err := resolveJobProject(ctx, q, req.ProjectID)
		if err != nil {
			return err
		}
		existing, found, err := prepareJobCreation(
			ctx, q, projectID, req, requestDigest, source,
		)
		if err != nil {
			return err
		}
		if found {
			result = existing
			return nil
		}

		var insertedID uuid.UUID
		query := `
			INSERT INTO build_jobs (
				id, project_id, requested_by_subject_id, idempotency_key,
				package_atom, state, request, request_digest,
				status_snapshot, status_digest, source, created_at, updated_at,
				minimum_executor_protocol, required_capabilities
			) VALUES (
				$1,
				$2::uuid,
				NULLIF($3, '')::uuid, NULLIF($4, ''), $5, $6, $7::jsonb, $8,
				$9::jsonb, $10, $11,
				CASE WHEN $11 = 'api' THEN clock_timestamp() ELSE $12 END,
				$13, $14, $15::jsonb
			)
			RETURNING id
		`
		if req.IdempotencyKey != "" {
			query = `
				INSERT INTO build_jobs (
					id, project_id, requested_by_subject_id, idempotency_key,
					package_atom, state, request, request_digest,
					status_snapshot, status_digest, source, created_at, updated_at,
					minimum_executor_protocol, required_capabilities
				) VALUES (
					$1,
					$2::uuid,
					NULLIF($3, '')::uuid, $4, $5, $6, $7::jsonb, $8,
					$9::jsonb, $10, $11,
					CASE WHEN $11 = 'api' THEN clock_timestamp() ELSE $12 END,
					$13, $14, $15::jsonb
				)
				ON CONFLICT (project_id, idempotency_key)
				DO NOTHING
				RETURNING id
			`
		}
		err = q.QueryRow(ctx, query,
			status.JobID, projectID, req.RequestedBy, req.IdempotencyKey,
			req.PackageName, status.Status,
			string(requestJSON), requestDigest, string(statusJSON), statusDigest,
			source, status.CreatedAt, status.UpdatedAt, builder.ExecutorProtocolVersion,
			string(requirementsJSON),
		).Scan(&insertedID)
		if err == nil {
			result = builder.LedgerCreateResult{JobID: insertedID.String(), Status: status, Created: true}
			if status.Status != "queued" {
				if err := r.upsertAttemptSnapshot(ctx, q, status); err != nil {
					return err
				}
			}
			return r.insertJobEvent(ctx, q, status.JobID, "job.created", map[string]any{
				"state": status.Status, "request_digest": requestDigest,
				"status_digest": statusDigest, "source": source,
			})
		}
		if !errors.Is(err, pgx.ErrNoRows) || req.IdempotencyKey == "" {
			return fmt.Errorf("insert job ledger row: %w", err)
		}

		found, existing, err = loadIdempotentJob(
			ctx, q, projectID, req.IdempotencyKey, requestDigest,
		)
		if err != nil {
			return err
		}
		if !found {
			return fmt.Errorf("idempotency conflict did not return an existing job")
		}
		result = existing
		return nil
	})
	return result, err
}

func prepareJobCreation(
	ctx context.Context,
	q Querier,
	projectID string,
	req *builder.BuildRequest,
	requestDigest string,
	source string,
) (builder.LedgerCreateResult, bool, error) {
	if req.IdempotencyKey != "" {
		found, existing, err := loadIdempotentJob(
			ctx, q, projectID, req.IdempotencyKey, requestDigest,
		)
		if err != nil || found {
			return existing, found, err
		}
	}
	if source != "api" {
		return builder.LedgerCreateResult{}, false, nil
	}
	policy, err := lockSubmissionPolicy(ctx, q, projectID)
	if err != nil {
		return builder.LedgerCreateResult{}, false, err
	}
	// Another replica may have inserted the same key while this transaction
	// waited for the project policy lock.
	if req.IdempotencyKey != "" {
		found, existing, err := loadIdempotentJob(
			ctx, q, projectID, req.IdempotencyKey, requestDigest,
		)
		if err != nil || found {
			return existing, found, err
		}
	}
	if err := checkSubmissionAdmission(ctx, q, projectID, policy, req); err != nil {
		return builder.LedgerCreateResult{}, false, err
	}
	return builder.LedgerCreateResult{}, false, nil
}

func resolveJobProject(ctx context.Context, q Querier, requested string) (string, error) {
	var projectID string
	if strings.TrimSpace(requested) == "" {
		err := q.QueryRow(ctx, `
			SELECT id::text FROM projects WHERE name = $1
		`, DefaultProjectName).Scan(&projectID)
		if err != nil {
			return "", fmt.Errorf("resolve default project: %w", err)
		}
		return projectID, nil
	}
	if err := q.QueryRow(ctx, `
		SELECT id::text FROM projects WHERE id = $1
	`, requested).Scan(&projectID); err != nil {
		return "", fmt.Errorf("resolve build project: %w", err)
	}
	return projectID, nil
}

func loadIdempotentJob(
	ctx context.Context,
	q Querier,
	projectID, key, requestDigest string,
) (bool, builder.LedgerCreateResult, error) {
	var existingID uuid.UUID
	var existingRequestDigest string
	var existingStatusJSON []byte
	err := q.QueryRow(ctx, `
		SELECT id, request_digest, status_snapshot
		FROM build_jobs
		WHERE project_id = $1 AND idempotency_key = $2
	`, projectID, key).Scan(&existingID, &existingRequestDigest, &existingStatusJSON)
	if errors.Is(err, pgx.ErrNoRows) {
		return false, builder.LedgerCreateResult{}, nil
	}
	if err != nil {
		return false, builder.LedgerCreateResult{}, fmt.Errorf("read idempotent job: %w", err)
	}
	if existingRequestDigest != requestDigest {
		return false, builder.LedgerCreateResult{}, builder.NewIdempotencyConflictError(
			fmt.Errorf("idempotency key already belongs to a different build request"),
		)
	}
	var existingStatus builder.BuildStatus
	if err := json.Unmarshal(existingStatusJSON, &existingStatus); err != nil {
		return false, builder.LedgerCreateResult{}, fmt.Errorf("decode idempotent job status: %w", err)
	}
	return true, builder.LedgerCreateResult{
		JobID: existingID.String(), Status: &existingStatus, Created: false,
	}, nil
}

type submissionPolicy struct {
	suspended       bool
	abuseUntil      *time.Time
	now             time.Time
	maxQueued       int
	maxDaily        int
	maxVCPUs        int
	maxMemoryMiB    int
	maxDiskGiB      int
	maxBuildSeconds int64
	maxCloudCost    int64
}

type resourceVector struct {
	VCPUs     int
	MemoryMiB int
	DiskGiB   int
}

// resourceVectorFromRequest turns the immutable, catalog-resolved machine
// specification into accounting units. Pre-catalog jobs are charged the
// built-in compatibility class; partially specified catalog resources fail
// closed rather than silently under-accounting capacity.
func resourceVectorFromRequest(req *builder.BuildRequest) (resourceVector, error) {
	const (
		legacyVCPUs     = 4
		legacyMemoryMiB = 8192
		legacyDiskGiB   = 50
	)
	if req == nil {
		return resourceVector{}, fmt.Errorf("resource accounting requires a build request")
	}
	spec := req.MachineSpec
	if len(spec) == 0 && req.ResolvedContext != nil {
		spec = req.ResolvedContext.MachineSpec
	}
	if len(spec) == 0 && req.ResourceClass == "" {
		return resourceVector{
			VCPUs: legacyVCPUs, MemoryMiB: legacyMemoryMiB, DiskGiB: legacyDiskGiB,
		}, nil
	}
	parse := func(key string) (int, error) {
		raw := strings.TrimSpace(spec[key])
		value, err := strconv.Atoi(raw)
		if err != nil || value <= 0 {
			return 0, fmt.Errorf("resource class %q has invalid or missing %s",
				req.ResourceClass, key)
		}
		return value, nil
	}
	vcpus, err := parse("cores")
	if err != nil {
		return resourceVector{}, err
	}
	memoryMiB, err := parse("memory")
	if err != nil {
		return resourceVector{}, err
	}
	diskGiB, err := parse("disk_size")
	if err != nil {
		return resourceVector{}, err
	}
	return resourceVector{VCPUs: vcpus, MemoryMiB: memoryMiB, DiskGiB: diskGiB}, nil
}

func lockSubmissionPolicy(
	ctx context.Context,
	q Querier,
	projectID string,
) (submissionPolicy, error) {
	var policy submissionPolicy
	if err := q.QueryRow(ctx, `
		SELECT suspended, max_queued_jobs, max_daily_submissions,
		       max_active_vcpus, max_active_memory_mib, max_active_disk_gib,
		       max_daily_build_seconds, max_daily_cloud_cost_microunits,
		       abuse_suspended_until, clock_timestamp()
		FROM project_policies
		WHERE project_id = $1
		FOR UPDATE
	`, projectID).Scan(
		&policy.suspended, &policy.maxQueued, &policy.maxDaily,
		&policy.maxVCPUs, &policy.maxMemoryMiB, &policy.maxDiskGiB,
		&policy.maxBuildSeconds, &policy.maxCloudCost,
		&policy.abuseUntil, &policy.now,
	); err != nil {
		return submissionPolicy{}, fmt.Errorf("lock project admission policy: %w", err)
	}
	return policy, nil
}

func checkSubmissionAdmission(
	ctx context.Context,
	q Querier,
	projectID string,
	policy submissionPolicy,
	request *builder.BuildRequest,
) error {
	if policy.suspended {
		return builder.NewAdmissionError(
			"project_suspended", 0, 0, 0,
			fmt.Errorf("project is suspended; new builds and retries are disabled"),
		)
	}
	if policy.abuseUntil != nil && policy.abuseUntil.After(policy.now) {
		return builder.NewAdmissionError(
			"project_abuse_suspended", 0, 0,
			policy.abuseUntil.Sub(policy.now),
			fmt.Errorf("project is temporarily suspended by the failure-storm gate until %s",
				policy.abuseUntil.UTC().Format(time.RFC3339)),
		)
	}
	if err := checkResourceRequestLimits(
		request, policy.maxVCPUs, policy.maxMemoryMiB, policy.maxDiskGiB,
	); err != nil {
		return err
	}
	if err := checkRuntimeRequestLimits(
		request, policy.maxBuildSeconds, policy.maxCloudCost,
	); err != nil {
		return err
	}
	var queued, daily int
	var dayEnds time.Time
	if err := q.QueryRow(ctx, `
		WITH day_window AS (
			SELECT
				(date_trunc('day', clock_timestamp() AT TIME ZONE 'UTC')
					AT TIME ZONE 'UTC') AS starts_at
		)
		SELECT
			(SELECT count(*) FROM build_jobs
			 WHERE project_id = $1 AND state = 'queued' AND legacy_visible = true),
			(SELECT count(*) FROM build_jobs
			 WHERE project_id = $1
			   AND created_at >= dw.starts_at
			   AND created_at < dw.starts_at + interval '1 day'),
			dw.starts_at + interval '1 day'
		FROM day_window dw
	`, projectID).Scan(&queued, &daily, &dayEnds); err != nil {
		return fmt.Errorf("read project admission usage: %w", err)
	}
	if queued >= policy.maxQueued {
		return builder.NewAdmissionError(
			"queued_limit_reached", policy.maxQueued, queued, 30*time.Second,
			fmt.Errorf("project queued-job limit reached (%d/%d)", queued, policy.maxQueued),
		)
	}
	if daily >= policy.maxDaily {
		retryAfter := time.Until(dayEnds)
		if retryAfter < time.Second {
			retryAfter = time.Second
		}
		return builder.NewAdmissionError(
			"daily_submission_limit_reached", policy.maxDaily, daily, retryAfter,
			fmt.Errorf("project UTC daily submission limit reached (%d/%d)", daily, policy.maxDaily),
		)
	}
	return nil
}

func checkRuntimeRequestLimits(
	request *builder.BuildRequest,
	maxBuildSeconds, maxCloudCost int64,
) error {
	spec, err := runtimeBudgetSpecFromRequest(request)
	if err != nil {
		return builder.NewAdmissionError(
			"runtime_budget_request_invalid", 0, 0, 0, err,
		)
	}
	if spec.MaxRuntimeSeconds > maxBuildSeconds {
		return builder.NewAdmissionError(
			"build_minute_request_exceeds_daily_limit",
			int(maxBuildSeconds), int(spec.MaxRuntimeSeconds), 0,
			fmt.Errorf("build reserves %d seconds but project UTC daily limit is %d seconds",
				spec.MaxRuntimeSeconds, maxBuildSeconds),
		)
	}
	if spec.ReservedCloudCostMicrounits > maxCloudCost {
		return builder.NewAdmissionError(
			"cloud_cost_request_exceeds_daily_limit",
			int(maxCloudCost), int(spec.ReservedCloudCostMicrounits), 0,
			fmt.Errorf("build reserves %d cloud-cost microunits but project UTC daily limit is %d",
				spec.ReservedCloudCostMicrounits, maxCloudCost),
		)
	}
	return nil
}

func checkResourceRequestLimits(
	request *builder.BuildRequest,
	maxVCPUs, maxMemoryMiB, maxDiskGiB int,
) error {
	resources, err := resourceVectorFromRequest(request)
	if err != nil {
		return builder.NewAdmissionError(
			"resource_request_invalid", 0, 0, 0, err,
		)
	}
	if resources.VCPUs > maxVCPUs {
		return builder.NewAdmissionError(
			"vcpu_request_exceeds_limit", maxVCPUs, resources.VCPUs, 0,
			fmt.Errorf("build requests %d vCPUs but project limit is %d",
				resources.VCPUs, maxVCPUs),
		)
	}
	if resources.MemoryMiB > maxMemoryMiB {
		return builder.NewAdmissionError(
			"memory_request_exceeds_limit", maxMemoryMiB, resources.MemoryMiB, 0,
			fmt.Errorf("build requests %d MiB memory but project limit is %d MiB",
				resources.MemoryMiB, maxMemoryMiB),
		)
	}
	if resources.DiskGiB > maxDiskGiB {
		return builder.NewAdmissionError(
			"disk_request_exceeds_limit", maxDiskGiB, resources.DiskGiB, 0,
			fmt.Errorf("build requests %d GiB disk but project limit is %d GiB",
				resources.DiskGiB, maxDiskGiB),
		)
	}
	return nil
}

// RecordTransition persists a status snapshot, attempt state, event, and
// outbox row atomically.
func (r *JobRepository) RecordTransition(ctx context.Context, previous, current *builder.BuildStatus) error {
	err := r.recordTransition(ctx, previous, current, "runtime")
	r.recordWrite(err)
	return err
}

func (r *JobRepository) recordTransition(ctx context.Context, previous, current *builder.BuildStatus, source string) error {
	statusJSON, statusDigest, err := statusDocument(current)
	if err != nil {
		return err
	}
	return r.db.WithTx(ctx, pgx.TxOptions{}, func(q Querier) error {
		transitionAt, err := readDatabaseClock(ctx, q)
		if err != nil {
			return err
		}
		var databaseState, databaseDigest string
		var revision int64
		if err := q.QueryRow(ctx, `
			SELECT state, status_digest, ledger_revision
			FROM build_jobs
			WHERE id = $1 AND legacy_visible = true
			FOR UPDATE
		`, current.JobID).Scan(&databaseState, &databaseDigest, &revision); err != nil {
			return fmt.Errorf("lock job ledger row: %w", err)
		}
		if databaseState == current.Status && databaseDigest == statusDigest {
			return nil
		}
		if previous != nil && databaseState != previous.Status {
			return fmt.Errorf("job %s ledger state is %s, expected %s", current.JobID, databaseState, previous.Status)
		}
		if err := validateTransitionClaim(ctx, q, current); err != nil {
			return err
		}

		revision++
		var completedAt any
		if isLedgerTerminal(current.Status) {
			completedAt = transitionAt
		}
		if _, err := q.Exec(ctx, `
			UPDATE build_jobs
			SET state = $2,
			    status_snapshot = $3::jsonb,
			    status_digest = $4,
			    terminal_reason = $5,
			    updated_at = $6,
			    completed_at = COALESCE($7, completed_at),
			    ledger_revision = $8
			WHERE id = $1
		`, current.JobID, current.Status, string(statusJSON), statusDigest,
			current.Error, transitionAt, completedAt, revision); err != nil {
			return fmt.Errorf("update job ledger row: %w", err)
		}

		if err := r.recordAttemptTransitionTx(
			ctx, q, current, transitionAt,
		); err != nil {
			return err
		}

		eventType := "job.snapshot_updated"
		if previous == nil || previous.Status != current.Status {
			eventType = "job.state_changed"
		}
		fromState := ""
		if previous != nil {
			fromState = previous.Status
		}
		return r.insertJobEvent(ctx, q, current.JobID, eventType, map[string]any{
			"from": fromState, "to": current.Status, "status_digest": statusDigest,
			"ledger_revision": revision, "source": source,
		})
	})
}

func validateTransitionClaim(
	ctx context.Context,
	q Querier,
	current *builder.BuildStatus,
) error {
	if current.AttemptID == "" {
		return nil
	}
	var active bool
	err := q.QueryRow(ctx, `
		SELECT l.expires_at > clock_timestamp()
		       AND l.fence_token = $3
		       AND w.stable_name = $4
		       AND u.state = 'active'
		       AND u.metering_started_at
		           + make_interval(secs => u.max_runtime_seconds::double precision)
		           > clock_timestamp()
		FROM build_attempts a
		JOIN worker_leases l ON l.attempt_id = a.id
		JOIN workers w ON w.id = l.worker_id
		JOIN project_attempt_usage u ON u.attempt_id = a.id
		WHERE a.id = $1 AND a.job_id = $2
		FOR UPDATE OF a, l
	`, current.AttemptID, current.JobID, current.FenceToken,
		current.LeaseOwner).Scan(&active)
	if errors.Is(err, pgx.ErrNoRows) {
		return fmt.Errorf("job %s durable claim is no longer active", current.JobID)
	}
	if err != nil {
		return fmt.Errorf("validate durable transition fence: %w", err)
	}
	if !active {
		return fmt.Errorf("job %s durable claim is stale or expired", current.JobID)
	}
	return nil
}

func (r *JobRepository) recordAttemptTransitionTx(
	ctx context.Context,
	q Querier,
	current *builder.BuildStatus,
	transitionAt time.Time,
) error {
	if current.AttemptID == "" {
		if current.Status == "queued" {
			return nil
		}
		return r.upsertAttemptSnapshot(ctx, q, current)
	}
	var finishedAt any
	if isLedgerTerminal(current.Status) {
		finishedAt = transitionAt
	}
	tag, err := q.Exec(ctx, `
		UPDATE build_attempts
		SET state = $2,
		    failure_detail = CASE WHEN $2 = 'failed' THEN $3 ELSE failure_detail END,
		    finished_at = COALESCE($4, finished_at),
		    updated_at = $5
		WHERE id = $1 AND job_id = $6 AND fence_token = $7
	`, current.AttemptID, current.Status, current.Error, finishedAt,
		transitionAt, current.JobID, current.FenceToken)
	if err != nil {
		return fmt.Errorf("update fenced build attempt: %w", err)
	}
	if tag.RowsAffected() != 1 {
		return fmt.Errorf("job %s fenced attempt was replaced", current.JobID)
	}
	if !isLedgerTerminal(current.Status) {
		if reservationPhase(current.Status) == "provision" {
			if err := markAttemptCloudStarted(
				ctx, q, current.AttemptID, transitionAt,
			); err != nil {
				return err
			}
		}
		return updateResourceReservationPhase(
			ctx, q, current.AttemptID, current.Status, transitionAt,
		)
	}
	reason := "job_" + current.Status
	if err := settleAttemptUsage(
		ctx, q, current.AttemptID, reason, current.Status, transitionAt,
	); err != nil {
		return err
	}
	if _, err := q.Exec(ctx,
		`DELETE FROM worker_leases WHERE attempt_id = $1`,
		current.AttemptID,
	); err != nil {
		return fmt.Errorf("release terminal worker lease: %w", err)
	}
	if err := releaseResourceReservation(
		ctx, q, current.AttemptID, reason, transitionAt,
	); err != nil {
		return err
	}
	if err := releaseArtifactBudgetReservation(
		ctx, q, current.AttemptID, reason, transitionAt,
	); err != nil {
		return err
	}
	if err := cancelPhaseWorkItems(
		ctx, q, current.AttemptID, reason, transitionAt,
	); err != nil {
		return err
	}
	return revokeWorkerGatewayAttempt(
		ctx, q, current.AttemptID, reason, transitionAt,
	)
}

func isLedgerTerminal(state string) bool {
	return state == "completed" || state == "success" || state == "failed" || state == "canceled"
}

func reservationPhase(state string) string {
	switch state {
	case "claimed":
		return "claimed"
	case "provisioning", "deploying":
		return "provision"
	case "forwarding", "building":
		return "build"
	case "collecting", "verifying":
		return "verify"
	case "signing", "publishing":
		return "publish"
	default:
		return ""
	}
}

func updateResourceReservationPhase(
	ctx context.Context,
	q Querier,
	attemptID, state string,
	changedAt time.Time,
) error {
	phase := reservationPhase(state)
	if phase == "" {
		return nil
	}
	var currentPhase, projectID string
	var limit int
	err := q.QueryRow(ctx, `
		SELECT r.phase, r.project_id::text,
		       CASE $2
		         WHEN 'claimed' THEN pp.max_claimed_attempts
		         WHEN 'provision' THEN pp.max_provision_attempts
		         WHEN 'build' THEN pp.max_build_attempts
		         WHEN 'verify' THEN pp.max_verify_attempts
		         WHEN 'publish' THEN pp.max_publish_attempts
		       END
		FROM project_resource_reservations r
		JOIN project_policies pp ON pp.project_id = r.project_id
		WHERE r.attempt_id = $1 AND r.state = 'active'
		FOR UPDATE OF pp, r
	`, attemptID, phase).Scan(&currentPhase, &projectID, &limit)
	if err != nil {
		return fmt.Errorf("lock project phase reservation: %w", err)
	}
	if currentPhase == phase {
		return nil
	}
	var used int
	if err := q.QueryRow(ctx, `
		SELECT count(*)
		FROM project_resource_reservations
		WHERE project_id = $1 AND state = 'active'
		  AND phase = $2 AND attempt_id <> $3
	`, projectID, phase, attemptID).Scan(&used); err != nil {
		return fmt.Errorf("read project phase usage: %w", err)
	}
	if used >= limit {
		return &builder.PhaseCapacityError{
			Phase: phase, Used: used, Limit: limit,
		}
	}
	if _, err := q.Exec(ctx, `
		UPDATE project_resource_reservations
		SET phase = $2, phase_updated_at = $3
		WHERE attempt_id = $1 AND state = 'active' AND phase <> $2
	`, attemptID, phase, changedAt); err != nil {
		return fmt.Errorf("update project resource reservation phase: %w", err)
	}
	return nil
}

func releaseResourceReservation(
	ctx context.Context,
	q Querier,
	attemptID, reason string,
	releasedAt time.Time,
) error {
	if _, err := q.Exec(ctx, `
		UPDATE project_resource_reservations
		SET state = 'released', released_at = $2, release_reason = $3
		WHERE attempt_id = $1 AND state = 'active'
	`, attemptID, releasedAt, reason); err != nil {
		return fmt.Errorf("release project resource reservation: %w", err)
	}
	return nil
}

func releaseArtifactBudgetReservation(
	ctx context.Context,
	q Querier,
	attemptID, reason string,
	releasedAt time.Time,
) error {
	if _, err := q.Exec(ctx, `
		UPDATE artifact_generation_reservations
		SET state = 'released', released_at = $2, updated_at = $2,
		    release_reason = $3
		WHERE attempt_id = $1 AND state = 'active'
	`, attemptID, releasedAt, reason); err != nil {
		return fmt.Errorf("release artifact generation reservations: %w", err)
	}
	if _, err := q.Exec(ctx, `
		UPDATE project_artifact_budgets
		SET state = 'released', active_bytes = 0, released_at = $2,
		    updated_at = $2, release_reason = $3
		WHERE attempt_id = $1 AND state = 'active'
	`, attemptID, releasedAt, reason); err != nil {
		return fmt.Errorf("release project artifact budget: %w", err)
	}
	return nil
}

func cancelPhaseWorkItems(
	ctx context.Context,
	q Querier,
	attemptID, reason string,
	finishedAt time.Time,
) error {
	if _, err := q.Exec(ctx, `
		UPDATE phase_work_items
		SET state = 'canceled', lease_expires_at = NULL,
		    finished_at = $2, updated_at = $2, error = $3
		WHERE attempt_id = $1
		  AND state IN ('blocked', 'ready', 'claimed')
	`, attemptID, finishedAt, reason); err != nil {
		return fmt.Errorf("cancel remaining phase work: %w", err)
	}
	return nil
}

func (r *JobRepository) upsertAttemptSnapshot(ctx context.Context, q Querier, status *builder.BuildStatus) error {
	var finishedAt any
	if isLedgerTerminal(status.Status) {
		finishedAt = status.UpdatedAt
	}
	if _, err := q.Exec(ctx, `
		INSERT INTO build_attempts (
			id, job_id, attempt_no, state, fence_token, failure_detail,
			started_at, finished_at, created_at, updated_at
		) VALUES ($1, $2, 1, $3, 1, $4, $5, $6, $5, $7)
		ON CONFLICT (job_id, attempt_no)
		DO UPDATE SET
			state = EXCLUDED.state,
			failure_detail = CASE
				WHEN EXCLUDED.state = 'failed' THEN EXCLUDED.failure_detail
				ELSE build_attempts.failure_detail
			END,
			started_at = COALESCE(build_attempts.started_at, EXCLUDED.started_at),
			finished_at = COALESCE(EXCLUDED.finished_at, build_attempts.finished_at),
			updated_at = EXCLUDED.updated_at
	`, uuid.New(), status.JobID, status.Status, status.Error,
		status.CreatedAt, finishedAt, status.UpdatedAt); err != nil {
		return fmt.Errorf("upsert build attempt snapshot: %w", err)
	}
	return nil
}

// HideJob retains audit history while removing a terminal job from the legacy
// list/reconcile set.
func (r *JobRepository) HideJob(ctx context.Context, status *builder.BuildStatus, reason string) error {
	err := r.db.WithTx(ctx, pgx.TxOptions{}, func(q Querier) error {
		tag, err := q.Exec(ctx, `
			UPDATE build_jobs
			SET legacy_visible = false, deleted_at = now(), updated_at = now(),
			    ledger_revision = ledger_revision + 1
			WHERE id = $1 AND legacy_visible = true
		`, status.JobID)
		if err != nil {
			return err
		}
		if tag.RowsAffected() != 1 {
			return fmt.Errorf("job %s is missing or already hidden", status.JobID)
		}
		return r.insertJobEvent(ctx, q, status.JobID, "job.hidden", map[string]any{"reason": reason})
	})
	r.recordWrite(err)
	return err
}

// ExpireTerminal hides old terminal jobs from operator listings while
// retaining their attempts, events, logs, and artifact lineage for audit.
func (r *JobRepository) ExpireTerminal(ctx context.Context, before time.Time) (int, error) {
	var expired []string
	err := r.db.WithTx(ctx, pgx.TxOptions{}, func(q Querier) error {
		rows, err := q.Query(ctx, `
			UPDATE build_jobs
			SET legacy_visible = false, deleted_at = clock_timestamp(),
			    ledger_revision = ledger_revision + 1
			WHERE legacy_visible = true
			  AND state IN ('completed','success','failed','canceled')
			  AND updated_at < $1
			RETURNING id::text
		`, before)
		if err != nil {
			return err
		}
		for rows.Next() {
			var jobID string
			if err := rows.Scan(&jobID); err != nil {
				rows.Close()
				return err
			}
			expired = append(expired, jobID)
		}
		if err := rows.Err(); err != nil {
			rows.Close()
			return err
		}
		rows.Close()
		for _, jobID := range expired {
			if err := r.insertJobEvent(ctx, q, jobID, "job.retention_hidden", map[string]any{
				"before": before,
			}); err != nil {
				return err
			}
		}
		return nil
	})
	r.recordWrite(err)
	return len(expired), err
}

func (r *JobRepository) insertJobEvent(ctx context.Context, q Querier, jobID, eventType string, payload map[string]any) error {
	data, err := json.Marshal(payload)
	if err != nil {
		return err
	}
	if _, err := q.Exec(ctx, `
		INSERT INTO job_events (job_id, event_type, payload)
		VALUES ($1, $2, $3::jsonb)
	`, jobID, eventType, string(data)); err != nil {
		return fmt.Errorf("insert job event: %w", err)
	}
	if _, err := q.Exec(ctx, `
		INSERT INTO outbox_events (topic, aggregate_type, aggregate_id, payload)
		VALUES ($1, 'build_job', $2, $3::jsonb)
	`, eventType, jobID, string(data)); err != nil {
		return fmt.Errorf("insert outbox event: %w", err)
	}
	return nil
}

type ledgerRow struct {
	State         string
	RequestDigest string
	StatusDigest  string
	StatusJSON    []byte
}

// Reconcile is retained for migration-era repair tests and diagnostics. DB-4
// runtime projection reads PostgreSQL as authority and never calls this from
// the legacy JSON path.
func (r *JobRepository) Reconcile(ctx context.Context, jobs map[string]*builder.BuildStatus) (report LedgerReconcileReport) {
	report.CheckedAt = time.Now().UTC()
	report.LegacyCount = len(jobs)

	rows, err := r.db.pool.Query(ctx, `
		SELECT id::text, state, request_digest, status_digest, status_snapshot
		FROM build_jobs
		WHERE legacy_visible = true
	`)
	if err != nil {
		report.Error = err.Error()
		r.recordReconcile(report)
		return report
	}
	ledgerRows := make(map[string]ledgerRow)
	for rows.Next() {
		var id string
		var row ledgerRow
		if err := rows.Scan(&id, &row.State, &row.RequestDigest, &row.StatusDigest, &row.StatusJSON); err != nil {
			rows.Close()
			report.Error = err.Error()
			r.recordReconcile(report)
			return report
		}
		ledgerRows[id] = row
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		report.Error = err.Error()
		r.recordReconcile(report)
		return report
	}
	rows.Close()
	report.LedgerCount = len(ledgerRows)

	for id, status := range jobs {
		row, exists := ledgerRows[id]
		if !exists {
			report.Missing++
			req := status.Request
			if req == nil {
				req = &builder.BuildRequest{
					PackageName: status.PackageName, Version: status.Version, Arch: status.Arch,
					ResolvedContext: status.ResolvedContext,
				}
			}
			if _, err := r.createJob(ctx, req, status, "legacy_json"); err != nil {
				report.Error = err.Error()
				continue
			}
			report.Repaired++
			continue
		}
		delete(ledgerRows, id)

		_, wantedStatusDigest, digestErr := statusDocument(status)
		if digestErr != nil {
			report.Error = digestErr.Error()
			continue
		}
		statusMismatch := row.State != status.Status || row.StatusDigest != wantedStatusDigest
		requestMismatch := false
		if status.Request != nil {
			_, wantedRequestDigest, requestErr := requestDocument(status.Request)
			if requestErr != nil {
				report.Error = requestErr.Error()
				continue
			}
			requestMismatch = row.RequestDigest != wantedRequestDigest
		}
		if requestMismatch {
			report.RequestMismatch++
		}
		if !statusMismatch && !requestMismatch {
			continue
		}
		report.Mismatched++
		if err := r.repairJob(ctx, id, row, status, requestMismatch); err != nil {
			report.Error = err.Error()
			continue
		}
		report.Repaired++
	}
	report.Extra = len(ledgerRows)
	report.Consistent = report.Error == "" && report.Repaired == report.Missing+report.Mismatched && report.Extra == 0
	r.recordReconcile(report)
	return report
}

func (r *JobRepository) repairJob(ctx context.Context, jobID string, row ledgerRow, status *builder.BuildStatus, repairRequest bool) error {
	statusJSON, statusDigest, err := statusDocument(status)
	if err != nil {
		return err
	}
	var requestJSON []byte
	var requestDigest string
	if repairRequest {
		requestJSON, requestDigest, err = requestDocument(status.Request)
		if err != nil {
			return err
		}
	}
	return r.db.WithTx(ctx, pgx.TxOptions{}, func(q Querier) error {
		if repairRequest {
			if _, err := q.Exec(ctx, `
				UPDATE build_jobs
				SET state = $2, status_snapshot = $3::jsonb, status_digest = $4,
				    request = $5::jsonb, request_digest = $6, updated_at = $7,
				    ledger_revision = ledger_revision + 1
				WHERE id = $1
			`, jobID, status.Status, string(statusJSON), statusDigest,
				string(requestJSON), requestDigest, status.UpdatedAt); err != nil {
				return err
			}
		} else {
			if _, err := q.Exec(ctx, `
				UPDATE build_jobs
				SET state = $2, status_snapshot = $3::jsonb, status_digest = $4,
				    updated_at = $5, ledger_revision = ledger_revision + 1
				WHERE id = $1
			`, jobID, status.Status, string(statusJSON), statusDigest, status.UpdatedAt); err != nil {
				return err
			}
		}
		if status.Status != "queued" {
			if err := r.upsertAttemptSnapshot(ctx, q, status); err != nil {
				return err
			}
		}
		return r.insertJobEvent(ctx, q, jobID, "job.reconciled", map[string]any{
			"from": row.State, "to": status.Status, "request_repaired": repairRequest,
			"status_digest": statusDigest,
		})
	})
}

func (r *JobRepository) recordWrite(err error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	if builder.IsIdempotencyConflict(err) {
		// A valid client-side 409 proves the ledger was reachable and made a
		// deterministic comparison; it is not a storage write failure.
		return
	}
	if err != nil {
		r.stats.WriteErrors++
		r.stats.LastError = err.Error()
		return
	}
	r.stats.Writes++
	r.stats.LastWriteAt = time.Now().UTC()
	r.stats.LastError = ""
}

func (r *JobRepository) recordReconcile(report LedgerReconcileReport) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.stats.LastReconcile = report
	if report.Error != "" {
		r.stats.LastError = report.Error
	} else if report.Consistent {
		r.stats.LastError = ""
	}
}

// Status returns a concurrency-safe ledger status snapshot.
func (r *JobRepository) Status() JobLedgerStatus {
	r.mu.RLock()
	defer r.mu.RUnlock()
	return r.stats
}

func (r *JobRepository) RecordProjectionSync(err error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	if err != nil {
		r.stats.ProjectionErrors++
		r.stats.LastError = err.Error()
		return
	}
	r.stats.LastProjectionAt = time.Now().UTC()
	r.stats.LastError = ""
}
