package persistence

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"

	"github.com/slchris/portage-engine/internal/builder"
	"github.com/slchris/portage-engine/internal/catalog"
)

const maxLedgerErrorBytes = 64 * 1024

// LedgerReconcileReport compares the legacy in-memory view with visible
// PostgreSQL shadow rows. Missing/mismatched rows are repaired; extra rows are
// reported because DB-1 must not silently invent legacy queue ownership.
type LedgerReconcileReport struct {
	CheckedAt       time.Time `json:"checked_at"`
	LegacyCount     int       `json:"legacy_count"`
	LedgerCount     int       `json:"ledger_count"`
	Missing         int       `json:"missing"`
	Mismatched      int       `json:"mismatched"`
	RequestMismatch int       `json:"request_mismatch"`
	Extra           int       `json:"extra"`
	Repaired        int       `json:"repaired"`
	Consistent      bool      `json:"consistent"`
	Error           string    `json:"error,omitempty"`
}

// JobLedgerStatus is the low-cardinality runtime status exposed to health and
// the operator UI.
type JobLedgerStatus struct {
	Authority        string                `json:"authority"`
	Writes           uint64                `json:"writes"`
	WriteErrors      uint64                `json:"write_errors"`
	ProjectionErrors uint64                `json:"projection_errors"`
	LastWriteAt      time.Time             `json:"last_write_at,omitempty"`
	LastProjectionAt time.Time             `json:"last_projection_at,omitempty"`
	LastError        string                `json:"last_error,omitempty"`
	LastReconcile    LedgerReconcileReport `json:"last_reconcile"`
}

// JobRepository implements the DB-1 builder.JobLedger contract.
type JobRepository struct {
	db        *Database
	mu        sync.RWMutex
	stats     JobLedgerStatus
	workerMu  sync.Mutex
	workerIDs map[string]cachedWorker
}

type cachedWorker struct {
	ID        uuid.UUID
	Heartbeat time.Time
}

// NewJobRepository creates a shadow job ledger on an initialized DB-1 schema.
func NewJobRepository(db *Database) *JobRepository {
	return &JobRepository{
		db: db, stats: JobLedgerStatus{Authority: "postgresql"},
		workerIDs: make(map[string]cachedWorker),
	}
}

type storedBuildRequest struct {
	PackageName     string                        `json:"package_name"`
	Version         string                        `json:"version"`
	Arch            string                        `json:"arch"`
	UseFlags        []string                      `json:"use_flags"`
	CloudProvider   string                        `json:"cloud_provider"`
	ProfileID       string                        `json:"profile_id,omitempty"`
	RepositoryIDs   []string                      `json:"repository_ids,omitempty"`
	ResourceClass   string                        `json:"resource_class,omitempty"`
	MachineSpec     map[string]string             `json:"machine_spec"`
	ResolvedContext *catalog.ResolvedBuildContext `json:"resolved_context,omitempty"`
	ConfigBundle    *builder.ConfigBundle         `json:"config_bundle,omitempty"`
	IdempotencyKey  string                        `json:"idempotency_key,omitempty"`
}

func requestDocument(req *builder.BuildRequest) ([]byte, string, error) {
	if req == nil {
		return nil, "", fmt.Errorf("nil build request")
	}
	doc := storedBuildRequest{
		PackageName: req.PackageName, Version: req.Version, Arch: req.Arch,
		UseFlags: append([]string(nil), req.UseFlags...), CloudProvider: req.CloudProvider,
		ProfileID: req.ProfileID, RepositoryIDs: append([]string(nil), req.RepositoryIDs...),
		ResourceClass: req.ResourceClass, MachineSpec: req.MachineSpec,
		ResolvedContext: req.ResolvedContext, ConfigBundle: req.ConfigBundle,
		IdempotencyKey: req.IdempotencyKey,
	}
	data, err := json.Marshal(doc)
	if err != nil {
		return nil, "", fmt.Errorf("marshal build request: %w", err)
	}

	// The stored request keeps complete runtime provenance, but idempotency
	// must ignore timestamps generated by resolution itself. Otherwise an
	// identical retry a millisecond later hashes differently and is rejected.
	var digestDoc map[string]any
	if err := json.Unmarshal(data, &digestDoc); err != nil {
		return nil, "", fmt.Errorf("prepare build request digest: %w", err)
	}
	if resolved, ok := digestDoc["resolved_context"].(map[string]any); ok {
		delete(resolved, "resolved_at")
	}
	if bundle, ok := digestDoc["config_bundle"].(map[string]any); ok {
		if metadata, ok := bundle["metadata"].(map[string]any); ok {
			delete(metadata, "created_at")
		}
	}
	digestData, err := json.Marshal(digestDoc)
	if err != nil {
		return nil, "", fmt.Errorf("marshal build request digest: %w", err)
	}
	return data, digestBytes(digestData), nil
}

type storedJobStatus struct {
	JobID           string                        `json:"job_id"`
	Status          string                        `json:"status"`
	PackageName     string                        `json:"package_name"`
	Version         string                        `json:"version"`
	Arch            string                        `json:"arch"`
	CreatedAt       time.Time                     `json:"created_at"`
	UpdatedAt       time.Time                     `json:"updated_at"`
	InstanceID      string                        `json:"instance_id,omitempty"`
	Error           string                        `json:"error,omitempty"`
	ArtifactPath    string                        `json:"artifact_path,omitempty"`
	ArtifactURL     string                        `json:"artifact_url,omitempty"`
	Artifacts       []string                      `json:"artifacts,omitempty"`
	Signed          bool                          `json:"signed,omitempty"`
	ResolvedContext *catalog.ResolvedBuildContext `json:"resolved_context,omitempty"`
	FailedStage     string                        `json:"failed_stage,omitempty"`
}

func statusDocument(status *builder.BuildStatus) ([]byte, string, error) {
	if status == nil {
		return nil, "", fmt.Errorf("nil build status")
	}
	errorText := status.Error
	if len(errorText) > maxLedgerErrorBytes {
		errorText = errorText[:maxLedgerErrorBytes] + "\n[... error truncated in ledger ...]"
	}
	doc := storedJobStatus{
		JobID: status.JobID, Status: status.Status, PackageName: status.PackageName,
		Version: status.Version, Arch: status.Arch, CreatedAt: status.CreatedAt,
		UpdatedAt: status.UpdatedAt, InstanceID: status.InstanceID, Error: errorText,
		ArtifactPath: status.ArtifactPath, ArtifactURL: status.ArtifactURL,
		Artifacts: append([]string(nil), status.Artifacts...), Signed: status.Signed,
		ResolvedContext: status.ResolvedContext, FailedStage: status.FailedStage,
	}
	data, err := json.Marshal(doc)
	if err != nil {
		return nil, "", fmt.Errorf("marshal build status: %w", err)
	}
	return data, digestBytes(data), nil
}

func digestBytes(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

// CreateJob inserts a complete request and queued snapshot in one transaction,
// together with its event and outbox row.
func (r *JobRepository) CreateJob(ctx context.Context, req *builder.BuildRequest, status *builder.BuildStatus) (builder.LedgerCreateResult, error) {
	result, err := r.createJob(ctx, req, status, "api")
	r.recordWrite(err)
	return result, err
}

func (r *JobRepository) createJob(ctx context.Context, req *builder.BuildRequest, status *builder.BuildStatus, source string) (builder.LedgerCreateResult, error) {
	requestJSON, requestDigest, err := requestDocument(req)
	if err != nil {
		return builder.LedgerCreateResult{}, err
	}
	statusJSON, statusDigest, err := statusDocument(status)
	if err != nil {
		return builder.LedgerCreateResult{}, err
	}
	result := builder.LedgerCreateResult{}
	err = r.db.WithTx(ctx, pgx.TxOptions{}, func(q Querier) error {
		var insertedID uuid.UUID
		query := `
			INSERT INTO build_jobs (
				id, idempotency_key, package_atom, state, request, request_digest,
				status_snapshot, status_digest, source, created_at, updated_at
			) VALUES ($1, NULLIF($2, ''), $3, $4, $5::jsonb, $6, $7::jsonb, $8, $9, $10, $11)
			RETURNING id
		`
		if req.IdempotencyKey != "" {
			query = `
				INSERT INTO build_jobs (
					id, idempotency_key, package_atom, state, request, request_digest,
					status_snapshot, status_digest, source, created_at, updated_at
				) VALUES ($1, $2, $3, $4, $5::jsonb, $6, $7::jsonb, $8, $9, $10, $11)
				ON CONFLICT (idempotency_key)
					WHERE project_id IS NULL AND idempotency_key IS NOT NULL
				DO NOTHING
				RETURNING id
			`
		}
		err := q.QueryRow(ctx, query,
			status.JobID, req.IdempotencyKey, req.PackageName, status.Status,
			string(requestJSON), requestDigest, string(statusJSON), statusDigest,
			source, status.CreatedAt, status.UpdatedAt,
		).Scan(&insertedID)
		if err == nil {
			result = builder.LedgerCreateResult{JobID: insertedID.String(), Status: status, Created: true}
			if status.Status != "queued" {
				if err := r.upsertAttemptSnapshot(ctx, q, status); err != nil {
					return err
				}
			}
			return r.insertJobEvent(ctx, q, status.JobID, "job.created", map[string]any{
				"state": status.Status, "request_digest": requestDigest,
				"status_digest": statusDigest, "source": source,
			})
		}
		if !errors.Is(err, pgx.ErrNoRows) || req.IdempotencyKey == "" {
			return fmt.Errorf("insert job ledger row: %w", err)
		}

		var existingID uuid.UUID
		var existingRequestDigest string
		var existingStatusJSON []byte
		if err := q.QueryRow(ctx, `
			SELECT id, request_digest, status_snapshot
			FROM build_jobs
			WHERE project_id IS NULL AND idempotency_key = $1
		`, req.IdempotencyKey).Scan(&existingID, &existingRequestDigest, &existingStatusJSON); err != nil {
			return fmt.Errorf("read idempotent job: %w", err)
		}
		if existingRequestDigest != requestDigest {
			return builder.NewIdempotencyConflictError(
				fmt.Errorf("idempotency key already belongs to a different build request"),
			)
		}
		var existingStatus builder.BuildStatus
		if err := json.Unmarshal(existingStatusJSON, &existingStatus); err != nil {
			return fmt.Errorf("decode idempotent job status: %w", err)
		}
		result = builder.LedgerCreateResult{JobID: existingID.String(), Status: &existingStatus, Created: false}
		return nil
	})
	return result, err
}

// RecordTransition persists a status snapshot, attempt state, event, and
// outbox row atomically.
func (r *JobRepository) RecordTransition(ctx context.Context, previous, current *builder.BuildStatus) error {
	err := r.recordTransition(ctx, previous, current, "runtime")
	r.recordWrite(err)
	return err
}

func (r *JobRepository) recordTransition(ctx context.Context, previous, current *builder.BuildStatus, source string) error {
	statusJSON, statusDigest, err := statusDocument(current)
	if err != nil {
		return err
	}
	return r.db.WithTx(ctx, pgx.TxOptions{}, func(q Querier) error {
		var databaseState, databaseDigest string
		var revision int64
		if err := q.QueryRow(ctx, `
			SELECT state, status_digest, ledger_revision
			FROM build_jobs
			WHERE id = $1 AND legacy_visible = true
			FOR UPDATE
		`, current.JobID).Scan(&databaseState, &databaseDigest, &revision); err != nil {
			return fmt.Errorf("lock job ledger row: %w", err)
		}
		if databaseState == current.Status && databaseDigest == statusDigest {
			return nil
		}
		if previous != nil && databaseState != previous.Status {
			return fmt.Errorf("job %s ledger state is %s, expected %s", current.JobID, databaseState, previous.Status)
		}
		if current.AttemptID != "" {
			var active bool
			if err := q.QueryRow(ctx, `
				SELECT l.expires_at > clock_timestamp()
				       AND l.fence_token = $3
				       AND w.stable_name = $4
				FROM build_attempts a
				JOIN worker_leases l ON l.attempt_id = a.id
				JOIN workers w ON w.id = l.worker_id
				WHERE a.id = $1 AND a.job_id = $2
				FOR UPDATE OF a, l
			`, current.AttemptID, current.JobID, current.FenceToken, current.LeaseOwner).Scan(&active); err != nil {
				if errors.Is(err, pgx.ErrNoRows) {
					return fmt.Errorf("job %s durable claim is no longer active", current.JobID)
				}
				return fmt.Errorf("validate durable transition fence: %w", err)
			}
			if !active {
				return fmt.Errorf("job %s durable claim is stale or expired", current.JobID)
			}
		}

		revision++
		var completedAt any
		if isLedgerTerminal(current.Status) {
			completedAt = current.UpdatedAt
		}
		if _, err := q.Exec(ctx, `
			UPDATE build_jobs
			SET state = $2,
			    status_snapshot = $3::jsonb,
			    status_digest = $4,
			    terminal_reason = $5,
			    updated_at = $6,
			    completed_at = COALESCE($7, completed_at),
			    ledger_revision = $8
			WHERE id = $1
		`, current.JobID, current.Status, string(statusJSON), statusDigest,
			current.Error, current.UpdatedAt, completedAt, revision); err != nil {
			return fmt.Errorf("update job ledger row: %w", err)
		}

		if current.AttemptID != "" {
			var finishedAt any
			if isLedgerTerminal(current.Status) {
				finishedAt = current.UpdatedAt
			}
			tag, err := q.Exec(ctx, `
				UPDATE build_attempts
				SET state = $2,
				    failure_detail = CASE WHEN $2 = 'failed' THEN $3 ELSE failure_detail END,
				    finished_at = COALESCE($4, finished_at),
				    updated_at = $5
				WHERE id = $1 AND job_id = $6 AND fence_token = $7
			`, current.AttemptID, current.Status, current.Error, finishedAt,
				current.UpdatedAt, current.JobID, current.FenceToken)
			if err != nil {
				return fmt.Errorf("update fenced build attempt: %w", err)
			}
			if tag.RowsAffected() != 1 {
				return fmt.Errorf("job %s fenced attempt was replaced", current.JobID)
			}
			if isLedgerTerminal(current.Status) {
				if _, err := q.Exec(ctx, `DELETE FROM worker_leases WHERE attempt_id = $1`, current.AttemptID); err != nil {
					return fmt.Errorf("release terminal worker lease: %w", err)
				}
			}
		} else if current.Status != "queued" {
			if err := r.upsertAttemptSnapshot(ctx, q, current); err != nil {
				return err
			}
		}

		eventType := "job.snapshot_updated"
		if previous == nil || previous.Status != current.Status {
			eventType = "job.state_changed"
		}
		fromState := ""
		if previous != nil {
			fromState = previous.Status
		}
		return r.insertJobEvent(ctx, q, current.JobID, eventType, map[string]any{
			"from": fromState, "to": current.Status, "status_digest": statusDigest,
			"ledger_revision": revision, "source": source,
		})
	})
}

func isLedgerTerminal(state string) bool {
	return state == "completed" || state == "success" || state == "failed" || state == "canceled"
}

func (r *JobRepository) upsertAttemptSnapshot(ctx context.Context, q Querier, status *builder.BuildStatus) error {
	var finishedAt any
	if isLedgerTerminal(status.Status) {
		finishedAt = status.UpdatedAt
	}
	if _, err := q.Exec(ctx, `
		INSERT INTO build_attempts (
			id, job_id, attempt_no, state, fence_token, failure_detail,
			started_at, finished_at, created_at, updated_at
		) VALUES ($1, $2, 1, $3, 1, $4, $5, $6, $5, $7)
		ON CONFLICT (job_id, attempt_no)
		DO UPDATE SET
			state = EXCLUDED.state,
			failure_detail = CASE
				WHEN EXCLUDED.state = 'failed' THEN EXCLUDED.failure_detail
				ELSE build_attempts.failure_detail
			END,
			started_at = COALESCE(build_attempts.started_at, EXCLUDED.started_at),
			finished_at = COALESCE(EXCLUDED.finished_at, build_attempts.finished_at),
			updated_at = EXCLUDED.updated_at
	`, uuid.New(), status.JobID, status.Status, status.Error,
		status.CreatedAt, finishedAt, status.UpdatedAt); err != nil {
		return fmt.Errorf("upsert build attempt snapshot: %w", err)
	}
	return nil
}

// HideJob retains audit history while removing a terminal job from the legacy
// list/reconcile set.
func (r *JobRepository) HideJob(ctx context.Context, status *builder.BuildStatus, reason string) error {
	err := r.db.WithTx(ctx, pgx.TxOptions{}, func(q Querier) error {
		tag, err := q.Exec(ctx, `
			UPDATE build_jobs
			SET legacy_visible = false, deleted_at = now(), updated_at = now(),
			    ledger_revision = ledger_revision + 1
			WHERE id = $1 AND legacy_visible = true
		`, status.JobID)
		if err != nil {
			return err
		}
		if tag.RowsAffected() != 1 {
			return fmt.Errorf("job %s is missing or already hidden", status.JobID)
		}
		return r.insertJobEvent(ctx, q, status.JobID, "job.hidden", map[string]any{"reason": reason})
	})
	r.recordWrite(err)
	return err
}

// ExpireTerminal hides old terminal jobs from operator listings while
// retaining their attempts, events, logs, and artifact lineage for audit.
func (r *JobRepository) ExpireTerminal(ctx context.Context, before time.Time) (int, error) {
	var expired []string
	err := r.db.WithTx(ctx, pgx.TxOptions{}, func(q Querier) error {
		rows, err := q.Query(ctx, `
			UPDATE build_jobs
			SET legacy_visible = false, deleted_at = clock_timestamp(),
			    ledger_revision = ledger_revision + 1
			WHERE legacy_visible = true
			  AND state IN ('completed','success','failed','canceled')
			  AND updated_at < $1
			RETURNING id::text
		`, before)
		if err != nil {
			return err
		}
		for rows.Next() {
			var jobID string
			if err := rows.Scan(&jobID); err != nil {
				rows.Close()
				return err
			}
			expired = append(expired, jobID)
		}
		if err := rows.Err(); err != nil {
			rows.Close()
			return err
		}
		rows.Close()
		for _, jobID := range expired {
			if err := r.insertJobEvent(ctx, q, jobID, "job.retention_hidden", map[string]any{
				"before": before,
			}); err != nil {
				return err
			}
		}
		return nil
	})
	r.recordWrite(err)
	return len(expired), err
}

func (r *JobRepository) insertJobEvent(ctx context.Context, q Querier, jobID, eventType string, payload map[string]any) error {
	data, err := json.Marshal(payload)
	if err != nil {
		return err
	}
	if _, err := q.Exec(ctx, `
		INSERT INTO job_events (job_id, event_type, payload)
		VALUES ($1, $2, $3::jsonb)
	`, jobID, eventType, string(data)); err != nil {
		return fmt.Errorf("insert job event: %w", err)
	}
	if _, err := q.Exec(ctx, `
		INSERT INTO outbox_events (topic, aggregate_type, aggregate_id, payload)
		VALUES ($1, 'build_job', $2, $3::jsonb)
	`, eventType, jobID, string(data)); err != nil {
		return fmt.Errorf("insert outbox event: %w", err)
	}
	return nil
}

type ledgerRow struct {
	State         string
	RequestDigest string
	StatusDigest  string
	StatusJSON    []byte
}

// Reconcile is retained for migration-era repair tests and diagnostics. DB-4
// runtime projection reads PostgreSQL as authority and never calls this from
// the legacy JSON path.
func (r *JobRepository) Reconcile(ctx context.Context, jobs map[string]*builder.BuildStatus) (report LedgerReconcileReport) {
	report.CheckedAt = time.Now().UTC()
	report.LegacyCount = len(jobs)

	rows, err := r.db.pool.Query(ctx, `
		SELECT id::text, state, request_digest, status_digest, status_snapshot
		FROM build_jobs
		WHERE legacy_visible = true
	`)
	if err != nil {
		report.Error = err.Error()
		r.recordReconcile(report)
		return report
	}
	ledgerRows := make(map[string]ledgerRow)
	for rows.Next() {
		var id string
		var row ledgerRow
		if err := rows.Scan(&id, &row.State, &row.RequestDigest, &row.StatusDigest, &row.StatusJSON); err != nil {
			rows.Close()
			report.Error = err.Error()
			r.recordReconcile(report)
			return report
		}
		ledgerRows[id] = row
	}
	if err := rows.Err(); err != nil {
		rows.Close()
		report.Error = err.Error()
		r.recordReconcile(report)
		return report
	}
	rows.Close()
	report.LedgerCount = len(ledgerRows)

	for id, status := range jobs {
		row, exists := ledgerRows[id]
		if !exists {
			report.Missing++
			req := status.Request
			if req == nil {
				req = &builder.BuildRequest{
					PackageName: status.PackageName, Version: status.Version, Arch: status.Arch,
					ResolvedContext: status.ResolvedContext,
				}
			}
			if _, err := r.createJob(ctx, req, status, "legacy_json"); err != nil {
				report.Error = err.Error()
				continue
			}
			report.Repaired++
			continue
		}
		delete(ledgerRows, id)

		_, wantedStatusDigest, digestErr := statusDocument(status)
		if digestErr != nil {
			report.Error = digestErr.Error()
			continue
		}
		statusMismatch := row.State != status.Status || row.StatusDigest != wantedStatusDigest
		requestMismatch := false
		if status.Request != nil {
			_, wantedRequestDigest, requestErr := requestDocument(status.Request)
			if requestErr != nil {
				report.Error = requestErr.Error()
				continue
			}
			requestMismatch = row.RequestDigest != wantedRequestDigest
		}
		if requestMismatch {
			report.RequestMismatch++
		}
		if !statusMismatch && !requestMismatch {
			continue
		}
		report.Mismatched++
		if err := r.repairJob(ctx, id, row, status, requestMismatch); err != nil {
			report.Error = err.Error()
			continue
		}
		report.Repaired++
	}
	report.Extra = len(ledgerRows)
	report.Consistent = report.Error == "" && report.Repaired == report.Missing+report.Mismatched && report.Extra == 0
	r.recordReconcile(report)
	return report
}

func (r *JobRepository) repairJob(ctx context.Context, jobID string, row ledgerRow, status *builder.BuildStatus, repairRequest bool) error {
	statusJSON, statusDigest, err := statusDocument(status)
	if err != nil {
		return err
	}
	var requestJSON []byte
	var requestDigest string
	if repairRequest {
		requestJSON, requestDigest, err = requestDocument(status.Request)
		if err != nil {
			return err
		}
	}
	return r.db.WithTx(ctx, pgx.TxOptions{}, func(q Querier) error {
		if repairRequest {
			if _, err := q.Exec(ctx, `
				UPDATE build_jobs
				SET state = $2, status_snapshot = $3::jsonb, status_digest = $4,
				    request = $5::jsonb, request_digest = $6, updated_at = $7,
				    ledger_revision = ledger_revision + 1
				WHERE id = $1
			`, jobID, status.Status, string(statusJSON), statusDigest,
				string(requestJSON), requestDigest, status.UpdatedAt); err != nil {
				return err
			}
		} else {
			if _, err := q.Exec(ctx, `
				UPDATE build_jobs
				SET state = $2, status_snapshot = $3::jsonb, status_digest = $4,
				    updated_at = $5, ledger_revision = ledger_revision + 1
				WHERE id = $1
			`, jobID, status.Status, string(statusJSON), statusDigest, status.UpdatedAt); err != nil {
				return err
			}
		}
		if status.Status != "queued" {
			if err := r.upsertAttemptSnapshot(ctx, q, status); err != nil {
				return err
			}
		}
		return r.insertJobEvent(ctx, q, jobID, "job.reconciled", map[string]any{
			"from": row.State, "to": status.Status, "request_repaired": repairRequest,
			"status_digest": statusDigest,
		})
	})
}

func (r *JobRepository) recordWrite(err error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	if builder.IsIdempotencyConflict(err) {
		// A valid client-side 409 proves the ledger was reachable and made a
		// deterministic comparison; it is not a storage write failure.
		return
	}
	if err != nil {
		r.stats.WriteErrors++
		r.stats.LastError = err.Error()
		return
	}
	r.stats.Writes++
	r.stats.LastWriteAt = time.Now().UTC()
	r.stats.LastError = ""
}

func (r *JobRepository) recordReconcile(report LedgerReconcileReport) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.stats.LastReconcile = report
	if report.Error != "" {
		r.stats.LastError = report.Error
	} else if report.Consistent {
		r.stats.LastError = ""
	}
}

// Status returns a concurrency-safe ledger status snapshot.
func (r *JobRepository) Status() JobLedgerStatus {
	r.mu.RLock()
	defer r.mu.RUnlock()
	return r.stats
}

func (r *JobRepository) RecordProjectionSync(err error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	if err != nil {
		r.stats.ProjectionErrors++
		r.stats.LastError = err.Error()
		return
	}
	r.stats.LastProjectionAt = time.Now().UTC()
	r.stats.LastError = ""
}
